### ISSUE TITLE
Create Merge two sorted Linked List in cpp

### ISSUE THREAD

**Issue by Ambareen09** [aayushi1499/Hacktoberfest2021-DSA#167]

**Comment by hemangdtu** [comment]
I would like to work on this issue. Kindly assign it to me.

**Comment by r-guy** [comment]
Please assign me this issue. I can make a simple code for this.

**Comment by prachi996** [comment]
i want to contribute. please assign this to me

**Comment by Deeksharora** [comment]
i want to work on it, please assign this to me.
